default_agent: robot_vacuum_agent
agents:
  robot_vacuum_agent:
    name: robot_vacuum_agent
    language: python
    node_version: '20'
    entrypoint: /Users/willismt/Documents/ai-agent-guardrails/agent/agent.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_11
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/willismt/Documents/ai-agent-guardrails/agent
    aws:
      execution_role: arn:aws:iam::832211724792:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-8574060575
      execution_role_auto_create: false
      account: '832211724792'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-832211724792-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: robot_vacuum_agent-Z5XPW5DDJs
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:832211724792:runtime/robot_vacuum_agent-Z5XPW5DDJs
      agent_session_id: 941faeca-8642-4d35-a100-17466e32604a
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration:
      customJWTAuthorizer:
        discoveryUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_ZoJ0Y3WxH/.well-known/openid-configuration
        allowedAudience:
        - 3kig0rtqcon6uq1u4hldsqmmct
    request_header_configuration:
      requestHeaderAllowlist:
      - Authorization
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
